### ISSUE TITLE
Rationale behind ValueObjects

### ISSUE THREAD

**Issue by RobertLowe** [AdrianLopezGue/daruma-backend#17]
Hey, just curious, whats the rationale behind ValueObjects?

https://github.com/AdrianLopezGue/daruma-backend/tree/bc610c0463aa7d7ea888be0f19734a60478ee4a6/src/bill/domain/model

Why not just use regular types/inferfaces/classes?

I am probably missing some concept which I'm trying to learn, thank you.

**Comment by RobertLowe** [comment]
Did some research,

A value object like https://github.com/AdrianLopezGue/daruma-backend/blob/bc610c0463aa7d7ea888be0f19734a60478ee4a6/src/bill/domain/model/bill-amount.ts `BillAmount` makes sense as a ValueObject, but a Value Object  like BillId does not its a singular piece of information

Reference https://www.youtube.com/watch?v=OIZ-ROcMmI8

**Comment by AdrianLopezGue** [comment]
Hello @RobertLowe! Actually, _BillId_ is representing a singular piece of information (bill identifier), handling complex operations like creating an unique id (uuid) and giving a factory method to create an id from string (`fromString`). Inside _Bill_ aggregate, _BillId_ makes totally sense to be a value object because it is representing a domain concept about a bill and allowing it to be an identifiable entity.

It could have been represented as a common primitive variable like a string, but all this mentioned methods (creating an uuid and factory method) would go inside bill entity, violating in some way the [Single Responsability Principle](https://en.wikipedia.org/wiki/Single-responsibility_principle) because in this case, Bill would be in charge of doing tasks outside of its main responsability (represent a unique bill) and make it more complex, more difficult to test and refactor.

If you have any question, ask me whenever you want and thanks for reviewing my project! 😊

**Comment by kodeine** [comment]
@AdrianLopezGue we can also use [Tiny-Types](https://www.npmjs.com/package/tiny-types) pkg instead of using our own valueObject class
